import = [
  "~/.config/alacritty/themes/github-dark-default.toml"
  # "~/.config/alacritty/themes/github-light-default.toml"
]

[font]
normal = { family = "Cascadia Code" }
# normal = { family = "FantasqueSansM Nerd Font" }
# normal = { family = "FantasqueSansM Nerd Font" }
# normal = { family = "BlexMono Nerd Font Medium" }
# normal = { family = "BlexMono Nerd Font" }
size = 12.5

[window]
dynamic_padding = true
opacity = 1
blur = true
decorations = "none"

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = { blinking = "Always" }

# [env]
# term = "xterm-256color"
