
[font]
# normal = { family = "Cascadia Code" }
# normal = { family = "FantasqueSansM Nerd Font" }
# normal = { family = "FantasqueSansM Nerd Font" }
# normal = { family = "BlexMono Nerd Font Medium" }
# normal = { family = "BlexMono Nerd Font" }
normal = { family = "JetBrains Mono" }
size = 12
# size = 13

[window]
dynamic_padding = true
opacity = 1
blur = true
decorations = "none"

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = { blinking = "Always" }

[general]
import = [
  # "~/.config/alacritty/themes/github-dark-default.toml"
  # "~/.config/alacritty/themes/github-light-default.toml"
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

# [env]
# term = "xterm-256color"
